version: '3.9'

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - network_example

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb-example # sesuai nama service MongoDB
    depends_on:
      - mongodb-example
    networks:
      - network_example

networks:
  network_example:
    driver: bridge
